# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 彭波的博客
email: 1872862529@qq.com
link: http://pengbo.org
description: > # this means to ignore newlines until "baseurl:"
  一个钟爱于web开发的程序员，喜欢php，javaee,ruby ，
  渴望在web方向做出自己的成就，希望自己越走越远。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pengbo.org" # the base hostname & protocol for your site
twitter_username: pengbo 
github_username:  彭波

# Build settings
markdown: kramdown